#!/bin/sh
# docker-entrypoint.sh
# Tạo agent/.env từ Railway environment variables trước khi chạy Vibe-Trading
# Railway inject env vars vào container — Vibe-Trading đọc từ agent/.env

set -e

ENV_FILE="/app/agent/.env"

echo "Generating agent/.env from environment variables..."

cat > "$ENV_FILE" << EOF
# Auto-generated by docker-entrypoint.sh from Railway env vars
# Do not edit manually

# ── LLM Provider ─────────────────────────────────────────────────────────────
LANGCHAIN_PROVIDER=${LANGCHAIN_PROVIDER:-deepseek}
LANGCHAIN_MODEL_NAME=${LANGCHAIN_MODEL_NAME:-deepseek-chat}

# DeepSeek
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}

# OpenAI (nếu dùng)
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}

# Gemini (nếu dùng)
GEMINI_API_KEY=${GEMINI_API_KEY:-}

# OpenRouter (nếu dùng)
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}

# ── API Server ────────────────────────────────────────────────────────────────
API_AUTH_KEY=${API_AUTH_KEY:-}
CORS_ORIGINS=${CORS_ORIGINS:-*}
ENABLE_SESSION_RUNTIME=${ENABLE_SESSION_RUNTIME:-true}
EOF

echo "agent/.env created successfully."
echo "  Provider : ${LANGCHAIN_PROVIDER:-deepseek}"
echo "  Model    : ${LANGCHAIN_MODEL_NAME:-deepseek-chat}"
echo "  Auth Key : $([ -n "$API_AUTH_KEY" ] && echo 'set' || echo 'NOT SET (dev mode)')"

# Chạy command được truyền vào (vibe-trading serve ...)
exec "$@"
